spring.application.name=loja_virtual

spring.datasource.url=jdbc:postgresql://localhost:5433/loja_virtual?autoreconnect=true
spring.datasource.username=postgres
spring.datasource.password=Admin@DBA*2026
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.platform=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

server.servlet.context-path= /loja_virtual

##Tamanho maximo do arquivo para upload
spring.servlet.multipart.max-file-size = 10000KB
##Quantidades de requisiçoes que a aplicação vai suportar
spring.servlet.multipart.max-request-size= 10000KB
##Ativa o upload
spring.servlet.multipart.enabled=true

##Habilitar compressão de dados de envio e retorno
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
##Tamanho minimo de envio de arquivo comprimido
server.compression.min-response-size=1024
##Ativa o http2 performatico
server.http2.enabled=true

##Codificação de caracteres especiais Ç ou ã UTF-8 para request e response
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.force-request=true
server.servlet.encoding.force-response=true

##Pool de conexões
##Classe que será responsavel pelo pool
#spring.datasource.type=com.zaxxer.hiraki.HirakiDataSource
##Numero maximo de milissegundos que um cliente aguardará por uma conexão
spring.datasource.hiraki.connection-timeout = 20000
##Numero minimo de conexoes inativas mantidas pelo HirakiCP em um conjunto de conexoes
spring.datasource.hiraki.minimum-idle = 200
##Máximo de pool de conexao
spring.datasource.hiraki.maximum-pool-size = 550
##Tempo ociosos para conexao
spring.datasource.hiraki.idle-timeout = 10000
spring.datasource.hiraki.pool-name = PoolHiraki
##Pool de processos internos no banco de dados
spring.datasource.dbcp2.pool-prepared-statements=true
spring.datasource.dbcp2.max-open-prepared-statements=550

##Salvando dados no banco automaticamente
spring.datasource.hiraki.auto-commit=false
server.servlet.session.timeout=240m
spring.transaction.rollback-on-commit-failure=true
spring.jpa.properties.hibernate.jdbc.batch_size = 4
spring.jpa.properties.hibernate.order_inserts = true
spring.jpa.properties.hibernate.order_updates = true
server.tomcat.max-connections=50000
server.tomcat.threads.min-spare=1000
spring.session.jdbc.cleanup-cron=0 0 4 * * *

